---
title: "Humpback predictions - compare to prey maps"
author: "Sam Woodman"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

In this document, we create yearly maps of humpback predictions averaged from April - June. These maps will be displayed as a multipanel (facet) plot to compare with the prey field maps from Santora et al 2020. 

```{r intro, message = FALSE}
library(eSDM)
library(lubridate)
library(RColorBrewer)
library(rnaturalearth)
library(sf)
library(tidyverse)
library(tmap)

#TODO: add user thing and incorporate monthly preds for consistency

source("User_script_local.R")
if (user == "KAF") {
  
  
} else if (user == "SMW") {
  path.mn.monthly <- "C:/SMW/RAIMBOW/Mn3kmSDM/Ignore/Data/Mn_3km_monthly.RDS"
  plot.path <- "C:/SMW/RAIMBOW/raimbow-local/Plots/Plots_KAF/Multipanel/Mn_3km_Apr-Jun_zoomed.png" #NULL
}
```

First, we read in the monthly humpback predictions, filter for the study area, and prep the sf object.

```{r preds}
x.orig <- readRDS(path.mn.monthly) 
x <- x.orig %>% filter(between(mlat, 36, 40))

x.meanall <- x %>% 
  group_by(pixel, mlat, mlon, areakm) %>% 
  summarise(mn_avgdens = mean(mn_avgdens)) %>% 
  ungroup() %>% 
  mutate(year = "All")

# Make sf object
x.geom <- x.orig %>% 
  select(mlon, mlat, pixel) %>% 
  distinct() %>% 
  pts2poly_centroids(0.027, crs = 4326, agr = "constant")

x.tojoin <- x %>% 
  select(-col_name, -month) %>% 
  mutate(year = as.character(year))
x.sf <- x.meanall %>% 
  bind_rows(x.tojoin) %>% 
  mutate(year = factor(year, levels = c("All", 2005:2018))) %>% 
  left_join(x.geom, by = "pixel") %>% 
  st_as_sf(crs = 4326, agr = "constant") %>% 
  select(year, mn_avgdens, pixel)
```

## Plot

Now we plot things

```{r, fig.width=16, fig.height=9}
### Plot prep
tmap_mode("plot")
col.breaks <- c(0, 0.01, 0.02, 0.03, 0.05, 0.08)
col.pal <- rev(brewer.pal(length(col.breaks) - 1, "YlGnBu"))

rmap.base <- st_geometry(ne_states(country = "United States of America", returnclass = "sf")) %>% 
  st_geometry() %>% 
  st_crop(x.sf)
# rmap.base2 <- ne_countries(scale = 10, continent = "North America", returnclass = "sf") %>% 
#   filter(admin %in% c("Canada", "Mexico")) %>% 
#   st_geometry()

### Plot
x.toplot <- x.sf %>%
  filter(!is.na(mn_avgdens), year == 2008)

tm.obj <- tm_shape(rmap.base, bbox = st_bbox(x.sf)) + 
  tm_polygons() +
  tm_shape(x.toplot) + 
  tm_fill(col = "mn_avgdens", border.col = "transparent",
          style = "fixed", breaks = col.breaks, palette = col.pal, 
          colorNA = NULL, showNA = FALSE, 
          title = "Whales / km2", legend.reverse = TRUE) + 
  tm_facets(by = "year", nrow = 3, ncol = 5,
            free.coords = FALSE, free.scales = FALSE) +
  tm_legend(outside = TRUE, position = c("right", "center"), outside.size = 0.2,
            text.size = 2, title.size = 3) +
  # # Issue: graticules span the facet boxes, but the map does not..
  # tm_graticules(ticks = TRUE, lines = FALSE, n.y = 5, n.x = 5, labels.size = 1)
  tm_layout(panel.label.size = 2.3)


tm.obj

if (!is.null(plot.path)) 
  tmap_save(tm.obj, filename = plot.path, width = 16, height = 9, units = "in", dpi = 300)
```
